---
- name: Check disk usage of vda1 and alert if over 75%
  hosts: webservers
  become: yes
  tasks:
    - name: Check disk usage of vda1
      shell: "df -h /dev/vda1 | awk 'NR==2 {print $5}' | sed 's/%//'"
      register: disk_usage

    - name: Alert if disk usage of vda1 is over 75%
      debug:
        msg: "Disk usage on /dev/vda1 is at {{ disk_usage.stdout }}%"
      when: "disk_usage.stdout | int > 75"
