---
- name: Check Disk Space Usage
  hosts: SG1
  tasks:
          - name: Disk usage from command module
            ansible.builtin.command: df -h
            register: space
          - ansible.builtin.debug:
                  var: space
