---
- name: Check WP Integrity
  hosts: webservers
  tasks:
          - name: Check WordPress Integrity
            ansible.builtin.command: gp wp wpagencysupport.com core verify-checksums
            register: OK
          - ansible.builtin.debug:
                  var: OK