---
- name: Check disk usage of vda1 and alert if over 75%
  hosts: ubuntu_servers
  become: yes
  vars:
    teams_webhook_url: "https://rocketwplimited.webhook.office.com/webhookb2/2185f0da-502f-4a3f-b435-3c14e7a154b3@4963f8a3-9dbf-444f-aed6-754777afe177/IncomingWebhook/cb802ad2fb9e486ca90ab6de2fc601c4/9ce1a27b-d314-4803-9bea-b449036d1b9f/V2z-Vu5hxujeqBUwjGTxHS_7vFEYy54A3xXTD0ksyS7oI1"
  tasks:"
  tasks:
    - name: Check disk usage of vda1
      shell: "df -h /dev/vda1 | awk 'NR==2 {print $5}' | sed 's/%//'"
      register: disk_usage

    - name: Send alert to Teams if disk usage of vda1 is over 75%
      uri:
        url: "{{ teams_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: >
          {
            "title": "Disk Space Alert",
            "text": "Disk usage on /dev/vda1 is at {{ disk_usage.stdout }}% on server {{ ansible_default_ipv4.address }}"
          }
        body_format: json
      when: "disk_usage.stdout | int > 75"
