---
- name: Scan server for WordPress installations and list them
  hosts: webservers
  become: yes
  tasks:
    - name: Find WordPress installations
      find:
        paths: /var/www
        patterns: wp-config.php
        recurse: yes
      register: wp_sites

    - name: Debug find results
      debug:
        var: wp_sites

    - name: List found WordPress installations
      debug:
        msg: "Found WordPress installation at {{ item.path | dirname }}"
      with_items: "{{ wp_sites.files }}"
      when: wp_sites.matched > 0
