---
- name: Scan for WordPress sites and update plugins
  hosts: webservers
  become: yes
  tasks:
    - name: Find WordPress installations
      find:
        paths: /var/www
        patterns: wp-config.php
      register: wp_sites

    - name: Update plugins for each WordPress site
      block:
        - name: Change to WordPress directory
          command: chdir={{ item.path | dirname }}
          with_items: "{{ wp_sites.files }}"
          register: wp_dirs

        - name: Update WordPress plugins
          command: wp plugin update --all
          with_items: "{{ wp_dirs.results }}"
          when: item.rc == 0
      when: wp_sites.matched > 0
