---
- name: Scan for WordPress updates and apply them
  hosts: webservers
  become: yes
  vars:
    teams_webhook_url: "https://rocketwplimited.webhook.office.com/webhookb2/2185f0da-502f-4a3f-b435-3c14e7a154b3@4963f8a3-9dbf-444f-aed6-754777afe177/IncomingWebhook/cb802ad2fb9e486ca90ab6de2fc601c4/9ce1a27b-d314-4803-9bea-b449036d1b9f/V2z-Vu5hxujeqBUwjGTxHS_7vFEYy54A3xXTD0ksyS7oI1"
  tasks:
    - name: Find WordPress installations
      find:
        paths: /var/www
        patterns: wp-config.php
        recurse: yes
      register: wp_sites

    - name: Update plugins for each WordPress site
      block:
        - name: Change to WordPress directory
          command: chdir={{ item.path | dirname }}
          with_items: "{{ wp_sites.files }}"
          register: wp_dirs

        - name: Update WordPress plugins
          command: gp {{ dirname }} wp plugin update --all --format=json
          with_items: "{{ wp_dirs.results }}"
          when: item.rc == 0
          register: update_results
          ignore_errors: yes

        - name: Collect update results
          set_fact:
            updates: "{{ updates | default([]) + [{'site': item.item.path | dirname, 'result': item.stdout | from_json}] }}"
          with_items: "{{ update_results.results }}"
          when: item.rc == 0

    - name: Send update results to Teams
      uri:
        url: "{{ teams_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: >
          {
            "title": "WordPress Plugin Updates",
            "text": "{{ updates | map('json_query', '[*].{site: site, plugins: result}') | list | to_nice_json }}"
          }
        body_format: json
      when: updates is defined
