---
- name: Scan for WordPress updates and apply them
  hosts: webservers
  become: yes
  vars:
    teams_webhook_url: "https://rocketwplimited.webhook.office.com/webhookb2/2185f0da-502f-4a3f-b435-3c14e7a154b3@4963f8a3-9dbf-444f-aed6-754777afe177/IncomingWebhook/cb802ad2fb9e486ca90ab6de2fc601c4/9ce1a27b-d314-4803-9bea-b449036d1b9f/V2z-Vu5hxujeqBUwjGTxHS_7vFEYy54A3xXTD0ksyS7oI1"
    log_file: "/var/log/wp_update_failures.log"
  tasks:
    - name: Find WordPress installations
      find:
        paths: /var/www
        patterns: wp-config.php
        recurse: yes
      register: wp_sites

    - name: Extract subdirectory names and paths
      set_fact:
        wp_sites_info: "{{ wp_sites.files | map(attribute='path') | map('dirname') | list }}"

    - name: Check and update WordPress plugins
      block:
        - name: Update WordPress plugins
          shell: >
            gp wp {{ item | basename }} --path={{ item }} plugin list --field=name --status=active --update=available |
            xargs -I {} gp wp {{ item | basename }} --path={{ item }} plugin update {}
          with_items: "{{ wp_sites_info }}"
          register: update_results
          ignore_errors: yes

        - name: Collect update results
          set_fact:
            updates: "{{ updates | default([]) + [{'site': item.item | basename, 'result': item.stdout, 'failed': item.rc != 0}] }}"
          with_items: "{{ update_results.results }}"

        - name: Log failed updates
          lineinfile:
            path: "{{ log_file }}"
            line: "Failed update on site {{ item.item | basename }}: {{ item.stdout }}"
            create: yes
          with_items: "{{ update_results.results }}"
          when: item.rc != 0
