---
- name: Scan for WordPress updates and apply them
  hosts: webservers
  become: yes
  vars:
    teams_webhook_url: "https://rocketwplimited.webhook.office.com/webhookb2/2185f0da-502f-4a3f-b435-3c14e7a154b3@4963f8a3-9dbf-444f-aed6-754777afe177/IncomingWebhook/cb802ad2fb9e486ca90ab6de2fc601c4/9ce1a27b-d314-4803-9bea-b449036d1b9f/V2z-Vu5hxujeqBUwjGTxHS_7vFEYy54A3xXTD0ksyS7oI1"

  tasks:
    - name: Find WordPress installations
      find:
        paths: /var/www
        patterns: wp-config.php
        recurse: yes
      register: wp_sites

    - name: Get WordPress site URLs (subdirectory names)
      set_fact:
        site_urls: "{{ wp_sites.files | map(attribute='path') | map('dirname') | map('basename') | list }}"

    - name: Check if URL is reachable
      uri:
        url: https://"{{ item }}"
        method: GET
        status_code: 200
        timeout: 10
      with_items: "{{ site_urls }}"
      register: url_check

    - name: Send Teams message if URL is down
      when: url_check.status != 200
      block:
        - name: Create message payload
          set_fact:
            teams_message: '{"text": "Alert: {{ item }} is down!"}'

        - name: Send message to Teams
          uri:
            url: "{{ teams_webhook_url }}"
            method: POST
            body: "{{ teams_message }}"
            headers:
              Content-Type: "application/json"
